// <auto-generated />
namespace Webcal.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAutoPrintLabels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAutoPrintLabels));
        
        string IMigrationMetadata.Id
        {
            get { return "201309031209347_AddAutoPrintLabels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
