//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webcal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify the given username and/or password.
        /// </summary>
        internal static string ERR_CANNOT_VERIFY_USERNAME_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_CANNOT_VERIFY_USERNAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF conversion error number: .
        /// </summary>
        internal static string ERR_CONVERSION_ERROR_NUMBER {
            get {
                return ResourceManager.GetString("ERR_CONVERSION_ERROR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change your password, please make sure your old password is correct..
        /// </summary>
        internal static string ERR_COULD_NOT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_COULD_NOT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish the temp directory.
        /// </summary>
        internal static string ERR_COULD_NOT_FIND_TEMP_DIR {
            get {
                return ResourceManager.GetString("ERR_COULD_NOT_FIND_TEMP_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week not recognised.
        /// </summary>
        internal static string ERR_DAY_OF_WEEK_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("ERR_DAY_OF_WEEK_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t reset your own password..
        /// </summary>
        internal static string ERR_DO_NOT_RESET_OWN_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_DO_NOT_RESET_OWN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given serial is invalid..
        /// </summary>
        internal static string ERR_GIVEN_SERIAL_IS_INVALID {
            get {
                return ResourceManager.GetString("ERR_GIVEN_SERIAL_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given license key has expired.
        /// </summary>
        internal static string ERR_LICENSE_KEY_HAS_EXPIRED {
            get {
                return ResourceManager.GetString("ERR_LICENSE_KEY_HAS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in as superuser to reset your password..
        /// </summary>
        internal static string ERR_PASSWORD_HAS_TO_BE_RESET_BY_SUPERUSER {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_HAS_TO_BE_RESET_BY_SUPERUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any matches.
        /// </summary>
        internal static string ERR_UNABLE_FIND_ANY_MATCHES {
            get {
                return ResourceManager.GetString("ERR_UNABLE_FIND_ANY_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate PDF.
        ///    
        ///{0}.
        /// </summary>
        internal static string ERR_UNABLE_GENERATE_PDF {
            get {
                return ResourceManager.GetString("ERR_UNABLE_GENERATE_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve calibration history from the smart card.
        ///
        ///This could be due to either;
        ///  An error reading the card
        ///  There is no calibration history present on the card..
        /// </summary>
        internal static string ERR_UNABLE_GET_CALIBRATION_HISTORY {
            get {
                return ResourceManager.GetString("ERR_UNABLE_GET_CALIBRATION_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the file specified..
        /// </summary>
        internal static string ERR_UNABLE_LOAD_GIVEN_FILE {
            get {
                return ResourceManager.GetString("ERR_UNABLE_LOAD_GIVEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve calibration history data..
        /// </summary>
        internal static string ERR_UNABLE_READ_CALIBRATION_HISTORY_DATA {
            get {
                return ResourceManager.GetString("ERR_UNABLE_READ_CALIBRATION_HISTORY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the smart card.  Please try again..
        /// </summary>
        internal static string ERR_UNABLE_READ_SMART_CARD {
            get {
                return ResourceManager.GetString("ERR_UNABLE_READ_SMART_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply transformations to the image..
        /// </summary>
        internal static string ERR_UNABLE_TO_APPLY_TRANSFORMATIONS {
            get {
                return ResourceManager.GetString("ERR_UNABLE_TO_APPLY_TRANSFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the given file..
        /// </summary>
        internal static string ERR_UNABLE_TO_LOAD_THE_SPECIFIED_FILE {
            get {
                return ResourceManager.GetString("ERR_UNABLE_TO_LOAD_THE_SPECIFIED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform a backup.  Backups can only be created when working with SQL Server CE databases..
        /// </summary>
        internal static string EXC_CANNOT_BACKUP_DATABASE {
            get {
                return ResourceManager.GetString("EXC_CANNOT_BACKUP_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a program capable of opening PDF files..
        /// </summary>
        internal static string EXC_CANNOT_PRINT_PDF {
            get {
                return ResourceManager.GetString("EXC_CANNOT_PRINT_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate resource &apos;{0}&apos;.
        /// </summary>
        internal static string EXC_COULD_NOT_LOCATE_RESOURCE {
            get {
                return ResourceManager.GetString("EXC_COULD_NOT_LOCATE_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst trying to read the smart card..
        /// </summary>
        internal static string EXC_ERROR_WHILST_READING_SMART_CARD {
            get {
                return ResourceManager.GetString("EXC_ERROR_WHILST_READING_SMART_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image could not be loaded.
        /// </summary>
        internal static string EXC_IMAGE_COULD_NOT_BE_LOADED {
            get {
                return ResourceManager.GetString("EXC_IMAGE_COULD_NOT_BE_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that all fields are completed before adding.
        /// </summary>
        internal static string EXC_INCOMPLETE_FIELDS {
            get {
                return ResourceManager.GetString("EXC_INCOMPLETE_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that all required files are completed with a valid value.
        /// </summary>
        internal static string EXC_MISSING_FIELDS {
            get {
                return ResourceManager.GetString("EXC_MISSING_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card/reader was found..
        /// </summary>
        internal static string EXC_NO_SMART_CARD_READERS_FOUND {
            get {
                return ResourceManager.GetString("EXC_NO_SMART_CARD_READERS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add workshop card file.
        ///.
        /// </summary>
        internal static string EXC_UNABLE_ADD_WORKSHOP_CARD_FILE {
            get {
                return ResourceManager.GetString("EXC_UNABLE_ADD_WORKSHOP_CARD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the settings view.
        ///    .
        /// </summary>
        internal static string EXC_UNABLE_CREATE_SETTINGS_VIEW {
            get {
                return ResourceManager.GetString("EXC_UNABLE_CREATE_SETTINGS_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export PDF file.
        /// </summary>
        internal static string EXC_UNABLE_EXPORT_PDF {
            get {
                return ResourceManager.GetString("EXC_UNABLE_EXPORT_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find font &apos;Lucida Console&apos;.  Printing cannot continue.
        /// </summary>
        internal static string EXC_UNABLE_FIND_LABEL_FONT {
            get {
                return ResourceManager.GetString("EXC_UNABLE_FIND_LABEL_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate card dump.
        /// </summary>
        internal static string EXC_UNABLE_GENERATE_CARD_DUMP {
            get {
                return ResourceManager.GetString("EXC_UNABLE_GENERATE_CARD_DUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate Microsoft Excel spreadsheet..
        /// </summary>
        internal static string EXC_UNABLE_GENERATE_EXCEL_SPREADSHEET {
            get {
                return ResourceManager.GetString("EXC_UNABLE_GENERATE_EXCEL_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate print preview.
        /// </summary>
        internal static string EXC_UNABLE_GENERATE_PRINT_PREVIEW {
            get {
                return ResourceManager.GetString("EXC_UNABLE_GENERATE_PRINT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to preview the document.
        /// </summary>
        internal static string EXC_UNABLE_PREVIEW_DOCUMENT {
            get {
                return ResourceManager.GetString("EXC_UNABLE_PREVIEW_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print PDF.
        /// </summary>
        internal static string EXC_UNABLE_PRINT_PDF {
            get {
                return ResourceManager.GetString("EXC_UNABLE_PRINT_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create driver card file..
        /// </summary>
        internal static string EXC_UNABLE_TO_CREATE_DRIVER_CARD {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_CREATE_DRIVER_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create tachograph file.
        /// </summary>
        internal static string EXC_UNABLE_TO_CREATE_TACHOGRAPH_FILE {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_CREATE_TACHOGRAPH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify the database path.
        /// </summary>
        internal static string EXC_UNABLE_VERIFY_DATABASE_PATH {
            get {
                return ResourceManager.GetString("EXC_UNABLE_VERIFY_DATABASE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred..
        /// </summary>
        internal static string EXC_UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("EXC_UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find plugin for given task ({0}).
        /// </summary>
        internal static string EXEC_UNABLE_TO_FIND_PLUGIN {
            get {
                return ResourceManager.GetString("EXEC_UNABLE_TO_FIND_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified does not exist or you don&apos;t have permission to access it..
        /// </summary>
        internal static string MSG_EXC_CANNOT_ACCESS_FILE {
            get {
                return ResourceManager.GetString("MSG_EXC_CANNOT_ACCESS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software has been registered
        ///
        ///Expiration date: {0}.
        /// </summary>
        internal static string MSG_INF_SOFTWARE_HAS_BEEN_REGISTERED {
            get {
                return ResourceManager.GetString("MSG_INF_SOFTWARE_HAS_BEEN_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to back-up the database?.
        /// </summary>
        internal static string QTN_WOULD_YOU_LIKE_BACKUP_DATABASE {
            get {
                return ResourceManager.GetString("QTN_WOULD_YOU_LIKE_BACKUP_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported graphics|*.jpg;*.jpeg;*.png|JPEG (*.jpg;*.jpeg)|*.jpg;*.jpeg|Portable Network Graphic (*.png)|*.png.
        /// </summary>
        internal static string SELECT_BITMAP_IMAGE {
            get {
                return ResourceManager.GetString("SELECT_BITMAP_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Year.
        /// </summary>
        internal static string TXT_2_YEAR {
            get {
                return ResourceManager.GetString("TXT_2_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Year.
        /// </summary>
        internal static string TXT_6_YEAR {
            get {
                return ResourceManager.GetString("TXT_6_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALOGUE INSPECTIONS:.
        /// </summary>
        internal static string TXT_ANALOGUE_INSPECTIONS {
            get {
                return ResourceManager.GetString("TXT_ANALOGUE_INSPECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Analogue Tachograph Document.
        /// </summary>
        internal static string TXT_ANALOGUE_TACHOGRAPH_DOCUMENT {
            get {
                return ResourceManager.GetString("TXT_ANALOGUE_TACHOGRAPH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string TXT_AND {
            get {
                return ResourceManager.GetString("TXT_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised Tachograph Center:.
        /// </summary>
        internal static string TXT_AUTHORISED_TACHOGRAPH_CENTER {
            get {
                return ResourceManager.GetString("TXT_AUTHORISED_TACHOGRAPH_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised Testers Signature:.
        /// </summary>
        internal static string TXT_AUTHORISED_TESTERS_SIGNATURE {
            get {
                return ResourceManager.GetString("TXT_AUTHORISED_TESTERS_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        internal static string TXT_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Certificate.
        /// </summary>
        internal static string TXT_CERTIFICATE_TACHOGRAPH_DOCUMENT {
            get {
                return ResourceManager.GetString("TXT_CERTIFICATE_TACHOGRAPH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification of the inspection and sealing of tachograph and M1N1 adapter.
        /// </summary>
        internal static string TXT_CERTIFICATION_INSPECTION_SEALING_TACHOGRAPH_M1N1 {
            get {
                return ResourceManager.GetString("TXT_CERTIFICATION_INSPECTION_SEALING_TACHOGRAPH_M1N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string TXT_COLOR {
            get {
                return ResourceManager.GetString("TXT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour          {0}.
        /// </summary>
        internal static string TXT_COLOR_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_COLOR_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour           {0}.
        /// </summary>
        internal static string TXT_COLOUR_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_COLOUR_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?
        ///
        ///Any unsaved changes will be lost..
        /// </summary>
        internal static string TXT_CONFIRM_EXIT {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created reports per year and per customer - office: {0}.
        /// </summary>
        internal static string TXT_CREATED_REPORTS_PER_YEAR_PER_CUSTOMER {
            get {
                return ResourceManager.GetString("TXT_CREATED_REPORTS_PER_YEAR_PER_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string TXT_CUSTOMER {
            get {
                return ResourceManager.GetString("TXT_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER DETAILS:.
        /// </summary>
        internal static string TXT_CUSTOMER_DETAILS {
            get {
                return ResourceManager.GetString("TXT_CUSTOMER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer settings.
        /// </summary>
        internal static string TXT_CUSTOMER_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_CUSTOMER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataDirectory.
        /// </summary>
        internal static string TXT_DATA_DIRECTORY {
            get {
                return ResourceManager.GetString("TXT_DATA_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE: .
        /// </summary>
        internal static string TXT_DATE {
            get {
                return ResourceManager.GetString("TXT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of inspection.
        /// </summary>
        internal static string TXT_DATE_OF_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_DATE_OF_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string TXT_DEMO {
            get {
                return ResourceManager.GetString("TXT_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Digital initial calibration.
        /// </summary>
        internal static string TXT_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIGITAL CALIBRATIONS:.
        /// </summary>
        internal static string TXT_DIGITAL_INSPECTIONS {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INSPECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Digital Tachograph Document.
        /// </summary>
        internal static string TXT_DIGITAL_TACHOGRAPH_DOCUMENT {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TACHOGRAPH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Digital 2 year calibration.
        /// </summary>
        internal static string TXT_DIGITAL_TWO_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TWO_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Seal:  {0}.
        /// </summary>
        internal static string TXT_DISTRIBUTOR_SEAL {
            get {
                return ResourceManager.GetString("TXT_DISTRIBUTOR_SEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been sent to your default printer.
        /// </summary>
        internal static string TXT_DOCUMENT_PRINTED {
            get {
                return ResourceManager.GetString("TXT_DOCUMENT_PRINTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string TXT_DOCUMENT_TYPE {
            get {
                return ResourceManager.GetString("TXT_DOCUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string TXT_EMAIL {
            get {
                return ResourceManager.GetString("TXT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid license key and the field will turn green.
        /// </summary>
        internal static string TXT_ENTER_VALID_LICENSE_KEY {
            get {
                return ResourceManager.GetString("TXT_ENTER_VALID_LICENSE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid unique username, and a password..
        /// </summary>
        internal static string TXT_ERR_ENTER_UNIQUE_USERNAME {
            get {
                return ResourceManager.GetString("TXT_ERR_ENTER_UNIQUE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user from the right hand menu to remove..
        /// </summary>
        internal static string TXT_ERR_SELECT_USER_TO_REMOVE {
            get {
                return ResourceManager.GetString("TXT_ERR_SELECT_USER_TO_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT CALIBRATION DUE: .
        /// </summary>
        internal static string TXT_EXP {
            get {
                return ResourceManager.GetString("TXT_EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        internal static string TXT_EXPORT_COMPLETE {
            get {
                return ResourceManager.GetString("TXT_EXPORT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        internal static string TXT_GENERAL_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_GENERAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Report.
        /// </summary>
        internal static string TXT_GENERATED_REPORT {
            get {
                return ResourceManager.GetString("TXT_GENERATED_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating workshop card file....
        /// </summary>
        internal static string TXT_GENERATING_WORKSHOP_CARD_FILE {
            get {
                return ResourceManager.GetString("TXT_GENERATING_WORKSHOP_CARD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give inspection equipment.
        /// </summary>
        internal static string TXT_GIVE_INSPECTION_EQUIPMENT {
            get {
                return ResourceManager.GetString("TXT_GIVE_INSPECTION_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give inspection method.
        /// </summary>
        internal static string TXT_GIVE_INSPECTION_METHOD {
            get {
                return ResourceManager.GetString("TXT_GIVE_INSPECTION_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give make of tachograph.
        /// </summary>
        internal static string TXT_GIVE_MAKE_OF_TACHOGRAPH {
            get {
                return ResourceManager.GetString("TXT_GIVE_MAKE_OF_TACHOGRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give make of vehicle.
        /// </summary>
        internal static string TXT_GIVE_MAKE_OF_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_GIVE_MAKE_OF_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give model of tachograph.
        /// </summary>
        internal static string TXT_GIVE_MODEL_OF_TACHOGRAPH {
            get {
                return ResourceManager.GetString("TXT_GIVE_MODEL_OF_TACHOGRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give model of vehicle.
        /// </summary>
        internal static string TXT_GIVE_MODEL_OF_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_GIVE_MODEL_OF_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the name of the technician.
        /// </summary>
        internal static string TXT_GIVE_NAME_OF_TECHNICIAN {
            get {
                return ResourceManager.GetString("TXT_GIVE_NAME_OF_TECHNICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give tyre size.
        /// </summary>
        internal static string TXT_GIVE_TYRE_SIZE {
            get {
                return ResourceManager.GetString("TXT_GIVE_TYRE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GV 212.
        /// </summary>
        internal static string TXT_GV_212 {
            get {
                return ResourceManager.GetString("TXT_GV_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} imp/km.
        /// </summary>
        internal static string TXT_IMP_KM {
            get {
                return ResourceManager.GetString("TXT_IMP_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TXT_INFORMATION {
            get {
                return ResourceManager.GetString("TXT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection equipments.
        /// </summary>
        internal static string TXT_INSPECTION_EQUIPMENTS {
            get {
                return ResourceManager.GetString("TXT_INSPECTION_EQUIPMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection methods.
        /// </summary>
        internal static string TXT_INSPECTION_METHODS {
            get {
                return ResourceManager.GetString("TXT_INSPECTION_METHODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Installation / Initial calibration.
        /// </summary>
        internal static string TXT_INSTALLATION_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_INSTALLATION_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K: {0} imp/km.
        /// </summary>
        internal static string TXT_K_FACTOR_IMP_KM {
            get {
                return ResourceManager.GetString("TXT_K_FACTOR_IMP_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K: {0} imp/km.
        /// </summary>
        internal static string TXT_K_FACTOR_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_K_FACTOR_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L: {0} mm.
        /// </summary>
        internal static string TXT_L_FACTOR_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_L_FACTOR_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L: {0} mm.
        /// </summary>
        internal static string TXT_L_FACTOR_MM {
            get {
                return ResourceManager.GetString("TXT_L_FACTOR_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:{0}.
        /// </summary>
        internal static string TXT_LABEL_ADDRESS__ {
            get {
                return ResourceManager.GetString("TXT_LABEL_ADDRESS_!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Date:{0}.
        /// </summary>
        internal static string TXT_LABEL_CALIBRATION_DATE {
            get {
                return ResourceManager.GetString("TXT_LABEL_CALIBRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TXT_LABEL_COMPANY_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TXT_LABEL_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number: {0}.
        /// </summary>
        internal static string TXT_LABEL_CUSTOMER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Initial.
        /// </summary>
        internal static string TXT_LABEL_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital 2yr.
        /// </summary>
        internal static string TXT_LABEL_DIGITAL_TWO_YEAR {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_TWO_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Calibration.
        /// </summary>
        internal static string TXT_LABEL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K={0} imp/km.
        /// </summary>
        internal static string TXT_LABEL_K_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_K_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L={0} mm.
        /// </summary>
        internal static string TXT_LABEL_L_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_L_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Work.
        /// </summary>
        internal static string TXT_LABEL_MINOR_WORK {
            get {
                return ResourceManager.GetString("TXT_LABEL_MINOR_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration.
        /// </summary>
        internal static string TXT_LABEL_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal no={0}.
        /// </summary>
        internal static string TXT_LABEL_SEAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SEAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No: {0}.
        /// </summary>
        internal static string TXT_LABEL_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6yr Calibration.
        /// </summary>
        internal static string TXT_LABEL_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician ID:{0}.
        /// </summary>
        internal static string TXT_LABEL_TECHNICIAN_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_TECHNICIAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2yr Inspection.
        /// </summary>
        internal static string TXT_LABEL_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_LABEL_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre size: {0}.
        /// </summary>
        internal static string TXT_LABEL_TYRE_SIZE {
            get {
                return ResourceManager.GetString("TXT_LABEL_TYRE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN={0}.
        /// </summary>
        internal static string TXT_LABEL_VIN {
            get {
                return ResourceManager.GetString("TXT_LABEL_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VU Serial No:{0}.
        /// </summary>
        internal static string TXT_LABEL_VU_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_VU_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W={0} imp/km.
        /// </summary>
        internal static string TXT_LABEL_W_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_W_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop:{0}.
        /// </summary>
        internal static string TXT_LABEL_WORKSHOP_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_WORKSHOP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Key.
        /// </summary>
        internal static string TXT_LICENSE_KEY {
            get {
                return ResourceManager.GetString("TXT_LICENSE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal No:   .
        /// </summary>
        internal static string TXT_LICENSE_NO_MINIMAL {
            get {
                return ResourceManager.GetString("TXT_LICENSE_NO_MINIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal No:   .
        /// </summary>
        internal static string TXT_LICENSE_NUMBER_LABEL {
            get {
                return ResourceManager.GetString("TXT_LICENSE_NUMBER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string TXT_LOCATION {
            get {
                return ResourceManager.GetString("TXT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location         {0}.
        /// </summary>
        internal static string TXT_LOCATION_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_LOCATION_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location        {0}.
        /// </summary>
        internal static string TXT_LOCATION_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_LOCATION_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1N1 Adapter.
        /// </summary>
        internal static string TXT_M1N1_ADAPTER {
            get {
                return ResourceManager.GetString("TXT_M1N1_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1N1 S/N.
        /// </summary>
        internal static string TXT_M1N1_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_M1N1_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1N1 S/N:        {0}.
        /// </summary>
        internal static string TXT_M1N1_SERIAL_NUMBER_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_M1N1_SERIAL_NUMBER_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1N1 S/N:       {0}.
        /// </summary>
        internal static string TXT_M1N1_SERIAL_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_M1N1_SERIAL_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        internal static string TXT_MAIL_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_MAIL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make:.
        /// </summary>
        internal static string TXT_MAKE {
            get {
                return ResourceManager.GetString("TXT_MAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make and Model.
        /// </summary>
        internal static string TXT_MAKE_AND_MODEL {
            get {
                return ResourceManager.GetString("TXT_MAKE_AND_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal number   {0}.
        /// </summary>
        internal static string TXT_MINIMAL_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("TXT_MINIMAL_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Work.
        /// </summary>
        internal static string TXT_MINOR_WORK {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        internal static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Work Details:.
        /// </summary>
        internal static string TXT_MINOR_WORK_DETAILS_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mm.
        /// </summary>
        internal static string TXT_MM {
            get {
                return ResourceManager.GetString("TXT_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Tachograph Centre.
        /// </summary>
        internal static string TXT_NAME_OF_TACHOGRAPH_CENTER {
            get {
                return ResourceManager.GetString("TXT_NAME_OF_TACHOGRAPH_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TXT_NO {
            get {
                return ResourceManager.GetString("TXT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No path specified).
        /// </summary>
        internal static string TXT_NO_PATH_SPECIFIED {
            get {
                return ResourceManager.GetString("TXT_NO_PATH_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to export.
        /// </summary>
        internal static string TXT_NOTHING_TO_EXPORT {
            get {
                return ResourceManager.GetString("TXT_NOTHING_TO_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of documents.
        /// </summary>
        internal static string TXT_NUMBER_OF_DOCUMENTS {
            get {
                return ResourceManager.GetString("TXT_NUMBER_OF_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer reading:.
        /// </summary>
        internal static string TXT_ODOMETER_READING {
            get {
                return ResourceManager.GetString("TXT_ODOMETER_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string TXT_OFFICE {
            get {
                return ResourceManager.GetString("TXT_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {page} of {numpages}.
        /// </summary>
        internal static string TXT_PAGE_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("TXT_PAGE_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string TXT_PASSWORD_HAS_BEEN_CHANGED {
            get {
                return ResourceManager.GetString("TXT_PASSWORD_HAS_BEEN_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset to &quot;password&quot; (without quotation marks)..
        /// </summary>
        internal static string TXT_PASSWORD_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("TXT_PASSWORD_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string TXT_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TXT_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Plaque.
        /// </summary>
        internal static string TXT_PLAQUE_TACHOGRAPH_DOCUMENT {
            get {
                return ResourceManager.GetString("TXT_PLAQUE_TACHOGRAPH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer settings.
        /// </summary>
        internal static string TXT_PRINTER_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_PRINTER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string TXT_QUESTION {
            get {
                return ResourceManager.GetString("TXT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from card.
        /// </summary>
        internal static string TXT_READ_FROM_CARD {
            get {
                return ResourceManager.GetString("TXT_READ_FROM_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        internal static string TXT_READING {
            get {
                return ResourceManager.GetString("TXT_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Recalibration.
        /// </summary>
        internal static string TXT_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration.
        /// </summary>
        internal static string TXT_RECALIBRATION_CERTIFICATE {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register between.
        /// </summary>
        internal static string TXT_REGISTER_BETWEEN {
            get {
                return ResourceManager.GetString("TXT_REGISTER_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER OF TACHOGRAPH PLAQUES ISSUED.
        /// </summary>
        internal static string TXT_REGISTER_OF_TACHOGRAPH_PLAQUES_ISSUES {
            get {
                return ResourceManager.GetString("TXT_REGISTER_OF_TACHOGRAPH_PLAQUES_ISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration number.
        /// </summary>
        internal static string TXT_REGISTRATION_NUMBER {
            get {
                return ResourceManager.GetString("TXT_REGISTRATION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration settings.
        /// </summary>
        internal static string TXT_REGISTRATION_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_REGISTRATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Certificate.
        /// </summary>
        internal static string TXT_REPRINT_CERTIFICATE {
            get {
                return ResourceManager.GetString("TXT_REPRINT_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-print completed..
        /// </summary>
        internal static string TXT_REPRINT_COMPLETED {
            get {
                return ResourceManager.GetString("TXT_REPRINT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Plaque.
        /// </summary>
        internal static string TXT_REPRINT_LABEL {
            get {
                return ResourceManager.GetString("TXT_REPRINT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal Number of Tachograph Centre.
        /// </summary>
        internal static string TXT_SEAL_OF_TACHOGRAPH_CENTER {
            get {
                return ResourceManager.GetString("TXT_SEAL_OF_TACHOGRAPH_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer details on the right, or select a customer on the right to edit..
        /// </summary>
        internal static string TXT_SELECT_CUSTOMER_ON_LEFT {
            get {
                return ResourceManager.GetString("TXT_SELECT_CUSTOMER_ON_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the days of the week to perform an automatic backup..
        /// </summary>
        internal static string TXT_SELECT_DAYS_FOR_BACKUP {
            get {
                return ResourceManager.GetString("TXT_SELECT_DAYS_FOR_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number:.
        /// </summary>
        internal static string TXT_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number    {0}.
        /// </summary>
        internal static string TXT_SERIAL_NUMBER_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_SERIAL_NUMBER_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number   {0}.
        /// </summary>
        internal static string TXT_SERIAL_NUMBER_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_SERIAL_NUMBER_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set k factor:.
        /// </summary>
        internal static string TXT_SET_K_FACTOR {
            get {
                return ResourceManager.GetString("TXT_SET_K_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut settings.
        /// </summary>
        internal static string TXT_SHORTCUT_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_SHORTCUT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TXT_SIGNATURE_TECHNICIAN {
            get {
                return ResourceManager.GetString("TXT_SIGNATURE_TECHNICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature/{0}.
        /// </summary>
        internal static string TXT_SIGNATURE_TECHNICIAN_LARGE {
            get {
                return ResourceManager.GetString("TXT_SIGNATURE_TECHNICIAN_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - 6 year calibration.
        /// </summary>
        internal static string TXT_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillray.
        /// </summary>
        internal static string TXT_SKILLRAY {
            get {
                return ResourceManager.GetString("TXT_SKILLRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillray Demo Unlicensed Software.
        /// </summary>
        internal static string TXT_SKILLRAY_UNLICENSED_SOFTWARE {
            get {
                return ResourceManager.GetString("TXT_SKILLRAY_UNLICENSED_SOFTWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string TXT_SOFTWARE {
            get {
                return ResourceManager.GetString("TXT_SOFTWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TACHOGRAPH:.
        /// </summary>
        internal static string TXT_TACHOGRAPH {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph and M1N1 inspection plate.
        /// </summary>
        internal static string TXT_TACHOGRAPH_AND_M1N1_INSPECTION_PLATE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_AND_M1N1_INSPECTION_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TACHOGRAPH CALIBRATION CERTIFICATE.
        /// </summary>
        internal static string TXT_TACHOGRAPH_CALIBRATION_CERTIFICATE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_CALIBRATION_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph documents created by customer.
        /// </summary>
        internal static string TXT_TACHOGRAPH_DOCUMENTS_BY_CUSTOMER {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_DOCUMENTS_BY_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph documents created per year.
        /// </summary>
        internal static string TXT_TACHOGRAPH_DOCUMENTS_PER_YEAR {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_DOCUMENTS_PER_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph documents that will expire between {0} and {1} - office: {2}.
        /// </summary>
        internal static string TXT_TACHOGRAPH_DOCUMENTS_THAT_WILL_EXPIRE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_DOCUMENTS_THAT_WILL_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph Installation Plaque.
        /// </summary>
        internal static string TXT_TACHOGRAPH_INSTALLATION_PLAQUE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_INSTALLATION_PLAQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph make.
        /// </summary>
        internal static string TXT_TACHOGRAPH_MAKE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_MAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph makes and models.
        /// </summary>
        internal static string TXT_TACHOGRAPH_MAKES_MODELS {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_MAKES_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph model.
        /// </summary>
        internal static string TXT_TACHOGRAPH_MODEL {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph number.
        /// </summary>
        internal static string TXT_TACHOGRAPH_NUMBER {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph plaque.
        /// </summary>
        internal static string TXT_TACHOGRAPH_PLAQUE {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_PLAQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachograph Record Sheet.
        /// </summary>
        internal static string TXT_TACHOGRAPH_RECORD_SHEET {
            get {
                return ResourceManager.GetString("TXT_TACHOGRAPH_RECORD_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string TXT_TECHNICIAN {
            get {
                return ResourceManager.GetString("TXT_TECHNICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technicians.
        /// </summary>
        internal static string TXT_TECHNICIANS {
            get {
                return ResourceManager.GetString("TXT_TECHNICIANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - 2 year inspection.
        /// </summary>
        internal static string TXT_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TXT_TYPE {
            get {
                return ResourceManager.GetString("TXT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre L factor:.
        /// </summary>
        internal static string TXT_TYRE_L_FACTOR {
            get {
                return ResourceManager.GetString("TXT_TYRE_L_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre Size:.
        /// </summary>
        internal static string TXT_TYRE_SIZE {
            get {
                return ResourceManager.GetString("TXT_TYRE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre Size        {0}.
        /// </summary>
        internal static string TXT_TYRE_SIZE_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_TYRE_SIZE_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre Size       {0}.
        /// </summary>
        internal static string TXT_TYRE_SIZE_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_TYRE_SIZE_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre sizes.
        /// </summary>
        internal static string TXT_TYRE_SIZES {
            get {
                return ResourceManager.GetString("TXT_TYRE_SIZES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the restore operation..
        /// </summary>
        internal static string TXT_UNABLE_COMPLETE_RESTORE {
            get {
                return ResourceManager.GetString("TXT_UNABLE_COMPLETE_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate workshop card file..
        /// </summary>
        internal static string TXT_UNABLE_GENERATE_WORKSHOP_CARD {
            get {
                return ResourceManager.GetString("TXT_UNABLE_GENERATE_WORKSHOP_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read smart card..
        /// </summary>
        internal static string TXT_UNABLE_READ_SMART_CARD {
            get {
                return ResourceManager.GetString("TXT_UNABLE_READ_SMART_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the malfunction of the tachograph [{0} - {1}, {2}] installed into vehicle [{3}] the data recorded in the VU&apos;s memory was unable to be downloaded..
        /// </summary>
        internal static string TXT_UNDOWNLOADABILITY_LINE_1 {
            get {
                return ResourceManager.GetString("TXT_UNDOWNLOADABILITY_LINE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefore no downloaded data can be provided to the user of the VU..
        /// </summary>
        internal static string TXT_UNDOWNLOADABILITY_LINE_2 {
            get {
                return ResourceManager.GetString("TXT_UNDOWNLOADABILITY_LINE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This certificate provides the control authorities with confirmation that the data recorded in the unit is not available and was not downloadable from the VU when the vehicle was presented to the named Approved Tachograph Centre..
        /// </summary>
        internal static string TXT_UNDOWNLOADABILITY_LINE_3 {
            get {
                return ResourceManager.GetString("TXT_UNDOWNLOADABILITY_LINE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is to be retained by the vehicle operator for the required time period, and presented when requested as required in ECC Regulation 3821/85, Annex 1B..
        /// </summary>
        internal static string TXT_UNDOWNLOADABILITY_LINE_4 {
            get {
                return ResourceManager.GetString("TXT_UNDOWNLOADABILITY_LINE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature/{0}.
        /// </summary>
        internal static string TXT_UNDOWNLOADABILITY_SIGNATURE {
            get {
                return ResourceManager.GetString("TXT_UNDOWNLOADABILITY_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicensed.
        /// </summary>
        internal static string TXT_UNLICENSED {
            get {
                return ResourceManager.GetString("TXT_UNLICENSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unsaved changes will be lost...are you sure?.
        /// </summary>
        internal static string TXT_UNSAVED_CHANGES_WILL_BE_LOST {
            get {
                return ResourceManager.GetString("TXT_UNSAVED_CHANGES_WILL_BE_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string TXT_USER_MANAGEMENT {
            get {
                return ResourceManager.GetString("TXT_USER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE:.
        /// </summary>
        internal static string TXT_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle makes and models.
        /// </summary>
        internal static string TXT_VEHICLE_MAKES_MODELS {
            get {
                return ResourceManager.GetString("TXT_VEHICLE_MAKES_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN:.
        /// </summary>
        internal static string TXT_VIN {
            get {
                return ResourceManager.GetString("TXT_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: {0}.
        /// </summary>
        internal static string TXT_VIN_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_VIN_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: {0}.
        /// </summary>
        internal static string TXT_VIN_SMALL_LABEL {
            get {
                return ResourceManager.GetString("TXT_VIN_SMALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7
        ///Date.
        /// </summary>
        internal static string TXT_VOSA_DATE_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_DATE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///Invoice number.
        /// </summary>
        internal static string TXT_VOSA_INVOICE_NUMBER_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_INVOICE_NUMBER_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///L
        ///mm.
        /// </summary>
        internal static string TXT_VOSA_L_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_L_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Registration/
        ///Chassis No.
        /// </summary>
        internal static string TXT_VOSA_REGISTRATION_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_REGISTRATION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///Tachograph Details
        ///
        ///Type (+)      Head Serial No.
        /// </summary>
        internal static string TXT_VOSA_TACHOGRAPH_DETAILS_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_TACHOGRAPH_DETAILS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8
        ///Nom.
        ///Tech.
        ///Initials,
        ///login or
        ///smartcard
        ///number.
        /// </summary>
        internal static string TXT_VOSA_TECH_INITIALS_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_TECH_INITIALS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5
        ///W
        ///Turns/Km
        ///or
        ///Imp/Km.
        /// </summary>
        internal static string TXT_VOSA_TURNS_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_TURNS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4
        ///Type
        ///of
        ///Insp
        ///(#).
        /// </summary>
        internal static string TXT_VOSA_TYPE_INSPECTION_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_TYPE_INSPECTION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///Veh
        ///Type
        ///(~).
        /// </summary>
        internal static string TXT_VOSA_VEHICLE_TYPE_HEADER {
            get {
                return ResourceManager.GetString("TXT_VOSA_VEHICLE_TYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRN:.
        /// </summary>
        internal static string TXT_VRN {
            get {
                return ResourceManager.GetString("TXT_VRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W factor:.
        /// </summary>
        internal static string TXT_W_FACTOR {
            get {
                return ResourceManager.GetString("TXT_W_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W: {0} imp/km.
        /// </summary>
        internal static string TXT_W_FACTOR_IMP_KM {
            get {
                return ResourceManager.GetString("TXT_W_FACTOR_IMP_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W: {0} imp/km.
        /// </summary>
        internal static string TXT_W_FACTOR_MEDIUM_LABEL {
            get {
                return ResourceManager.GetString("TXT_W_FACTOR_MEDIUM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardwick Grange.
        /// </summary>
        internal static string TXT_WEBCAL_CITY {
            get {
                return ResourceManager.GetString("TXT_WEBCAL_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA1 4RF.
        /// </summary>
        internal static string TXT_WEBCAL_POSTCODE {
            get {
                return ResourceManager.GetString("TXT_WEBCAL_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 10.
        /// </summary>
        internal static string TXT_WEBCAL_STREET {
            get {
                return ResourceManager.GetString("TXT_WEBCAL_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rufford Court.
        /// </summary>
        internal static string TXT_WEBCAL_TOWN {
            get {
                return ResourceManager.GetString("TXT_WEBCAL_TOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcal.
        /// </summary>
        internal static string TXT_WEBCAL_WEBCALNAME {
            get {
                return ResourceManager.GetString("TXT_WEBCAL_WEBCALNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Carried Out:.
        /// </summary>
        internal static string TXT_WORK_CARRIED_OUT {
            get {
                return ResourceManager.GetString("TXT_WORK_CARRIED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop card file was generated..
        /// </summary>
        internal static string TXT_WORKSHOP_CARD_FILE_GENERATED {
            get {
                return ResourceManager.GetString("TXT_WORKSHOP_CARD_FILE_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop number:{0}.
        /// </summary>
        internal static string TXT_WORKSHOP_NUMBER {
            get {
                return ResourceManager.GetString("TXT_WORKSHOP_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop settings.
        /// </summary>
        internal static string TXT_WORKSHOP_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_WORKSHOP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string TXT_YEAR {
            get {
                return ResourceManager.GetString("TXT_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TXT_YES {
            get {
                return ResourceManager.GetString("TXT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture.
        /// </summary>
        internal static string WorkshopSettingsViewModel_OnBrowse_Select_a_picture {
            get {
                return ResourceManager.GetString("WorkshopSettingsViewModel_OnBrowse_Select_a_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture.
        /// </summary>
        internal static string WorkshopSettingsViewModel_OnBrowse_Select_an_advert {
            get {
                return ResourceManager.GetString("WorkshopSettingsViewModel_OnBrowse_Select_an_advert", resourceCulture);
            }
        }
    }
}
