// <auto-generated />
namespace Webcal.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EmailSettings_AddPersonaliseCheckBox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailSettings_AddPersonaliseCheckBox));
        
        string IMigrationMetadata.Id
        {
            get { return "201308271416352_EmailSettings_AddPersonaliseCheckBox"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
