// <auto-generated />
namespace Webcal.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSignatureCapture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSignatureCapture));
        
        string IMigrationMetadata.Id
        {
            get { return "201308201454077_AddSignatureCapture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
