//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcal.DataModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webcal.DataModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred and the application cannot continue.
        /// </summary>
        internal static string ERR_APPLICATION_CANNOT_CONTINUE {
            get {
                return ResourceManager.GetString("ERR_APPLICATION_CANNOT_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week not recognised.
        /// </summary>
        internal static string ERR_DAY_OF_WEEK_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("ERR_DAY_OF_WEEK_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to discard changes.
        /// </summary>
        internal static string ERR_UNABLE_DISCARD_CHANGES {
            get {
                return ResourceManager.GetString("ERR_UNABLE_DISCARD_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given document type was not recognised.
        /// </summary>
        internal static string EXC_DOCUMENT_TYPE_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("EXC_DOCUMENT_TYPE_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes.  Some data may have been lost..
        /// </summary>
        internal static string EXC_UNABLE_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("EXC_UNABLE_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the request to the database.
        ///
        ///{0}.
        /// </summary>
        internal static string EXC_UNABLE_TO_COMPLETE_REQUEST {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_COMPLETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst reading the card.  Some data may be missing or erroneous..
        /// </summary>
        internal static string EXC_UNABLE_TO_FULL_READ_SMART_CARD {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_FULL_READ_SMART_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete this action.  Error could not be logged to the database.
        ///
        ///{0}.
        /// </summary>
        internal static string EXC_UNLOGGABLE_EXCEPTION {
            get {
                return ResourceManager.GetString("EXC_UNLOGGABLE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user repository is required to create the super user account..
        /// </summary>
        internal static string EXC_USER_REPOSITORY_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EXC_USER_REPOSITORY_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Digital initial calibration.
        /// </summary>
        internal static string TXT_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Digital 2 year calibration.
        /// </summary>
        internal static string TXT_DIGITAL_TWO_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TWO_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G - goods vehicle.
        /// </summary>
        internal static string TXT_GOODS_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_GOODS_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Installation / Initial calibration.
        /// </summary>
        internal static string TXT_INSTALLATION_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_INSTALLATION_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        internal static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No path specified).
        /// </summary>
        internal static string TXT_NO_PATH_SPECIFIED {
            get {
                return ResourceManager.GetString("TXT_NO_PATH_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P - passenger vehicle.
        /// </summary>
        internal static string TXT_PASSENGER_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_PASSENGER_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Recalibration.
        /// </summary>
        internal static string TXT_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - 6 year calibration.
        /// </summary>
        internal static string TXT_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - 2 year inspection.
        /// </summary>
        internal static string TXT_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
    }
}
