//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TachographReader.DataModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TachographReader.DataModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred and the application cannot continue.
        /// </summary>
        public static string ERR_APPLICATION_CANNOT_CONTINUE {
            get {
                return ResourceManager.GetString("ERR_APPLICATION_CANNOT_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week not recognised.
        /// </summary>
        public static string ERR_DAY_OF_WEEK_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("ERR_DAY_OF_WEEK_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to discard changes.
        /// </summary>
        public static string ERR_UNABLE_DISCARD_CHANGES {
            get {
                return ResourceManager.GetString("ERR_UNABLE_DISCARD_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given document type was not recognised.
        /// </summary>
        public static string EXC_DOCUMENT_TYPE_NOT_RECOGNISED {
            get {
                return ResourceManager.GetString("EXC_DOCUMENT_TYPE_NOT_RECOGNISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes.  Some data may have been lost..
        /// </summary>
        public static string EXC_UNABLE_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("EXC_UNABLE_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the request to the database.
        ///
        ///{0}.
        /// </summary>
        public static string EXC_UNABLE_TO_COMPLETE_REQUEST {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_COMPLETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst reading the card.  Some data may be missing or erroneous..
        /// </summary>
        public static string EXC_UNABLE_TO_FULL_READ_SMART_CARD {
            get {
                return ResourceManager.GetString("EXC_UNABLE_TO_FULL_READ_SMART_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete this action.  Error could not be logged to the database.
        ///
        ///{0}.
        /// </summary>
        public static string EXC_UNLOGGABLE_EXCEPTION {
            get {
                return ResourceManager.GetString("EXC_UNLOGGABLE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user repository is required to create the super user account..
        /// </summary>
        public static string EXC_USER_REPOSITORY_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EXC_USER_REPOSITORY_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Mode Change.
        /// </summary>
        public static string TXT_ACTIVITY_MODE_CHANGE {
            get {
                return ResourceManager.GetString("TXT_ACTIVITY_MODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TXT_CANCEL {
            get {
                return ResourceManager.GetString("TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Digital initial calibration.
        /// </summary>
        public static string TXT_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Digital 2 year calibration.
        /// </summary>
        public static string TXT_DIGITAL_TWO_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TWO_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string TXT_FRIDAY {
            get {
                return ResourceManager.GetString("TXT_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G - goods vehicle.
        /// </summary>
        public static string TXT_GOODS_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_GOODS_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Installation / Initial calibration.
        /// </summary>
        public static string TXT_INSTALLATION_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_INSTALLATION_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        public static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string TXT_MONDAY {
            get {
                return ResourceManager.GetString("TXT_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No path specified).
        /// </summary>
        public static string TXT_NO_PATH_SPECIFIED {
            get {
                return ResourceManager.GetString("TXT_NO_PATH_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TXT_OK {
            get {
                return ResourceManager.GetString("TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P - passenger vehicle.
        /// </summary>
        public static string TXT_PASSENGER_VEHICLE {
            get {
                return ResourceManager.GetString("TXT_PASSENGER_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Recalibration.
        /// </summary>
        public static string TXT_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string TXT_SATURDAY {
            get {
                return ResourceManager.GetString("TXT_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIEMENS VDO.
        /// </summary>
        public static string TXT_SEED_SIEMENS_VDO {
            get {
                return ResourceManager.GetString("TXT_SEED_SIEMENS_VDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillray.
        /// </summary>
        public static string TXT_SEED_SKILLRAY {
            get {
                return ResourceManager.GetString("TXT_SEED_SKILLRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1318.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_2_MODEL {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_2_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1324.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_2_MODEL_2 {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_2_MODEL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1314.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_2_MODEL_3 {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_2_MODEL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1319.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_2_MODEL_4 {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_2_MODEL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE5000.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_3_MODEL_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_3_MODEL_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8400.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_3_MODEL_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_3_MODEL_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2400.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_3_MODEL_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_3_MODEL_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STONERIDGE.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDO.
        /// </summary>
        public static string TXT_SEED_TACHO_MAKE_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MAKE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1381.
        /// </summary>
        public static string TXT_SEED_TACHO_MODEL_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_TACHO_MODEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINO.
        /// </summary>
        public static string TXT_SEED_VEHICLE_10_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_10_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R SERIES.
        /// </summary>
        public static string TXT_SEED_VEHICLE_2_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_2_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G SERIES.
        /// </summary>
        public static string TXT_SEED_VEHICLE_2_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_2_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPRINTER.
        /// </summary>
        public static string TXT_SEED_VEHICLE_3_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_3_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATEGO.
        /// </summary>
        public static string TXT_SEED_VEHICLE_3_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_3_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AXOR.
        /// </summary>
        public static string TXT_SEED_VEHICLE_3_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_3_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTROS.
        /// </summary>
        public static string TXT_SEED_VEHICLE_3_MAKE_4_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_3_MAKE_4_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMIUM.
        /// </summary>
        public static string TXT_SEED_VEHICLE_4_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_4_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAGNUM.
        /// </summary>
        public static string TXT_SEED_VEHICLE_4_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_4_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        public static string TXT_SEED_VEHICLE_5_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_5_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FH.
        /// </summary>
        public static string TXT_SEED_VEHICLE_5_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_5_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM.
        /// </summary>
        public static string TXT_SEED_VEHICLE_5_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_5_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRALIS.
        /// </summary>
        public static string TXT_SEED_VEHICLE_6_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_6_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY.
        /// </summary>
        public static string TXT_SEED_VEHICLE_6_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_6_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUROCARGO.
        /// </summary>
        public static string TXT_SEED_VEHICLE_6_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_6_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGL.
        /// </summary>
        public static string TXT_SEED_VEHICLE_7_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_7_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGX.
        /// </summary>
        public static string TXT_SEED_VEHICLE_7_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_7_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D MAX.
        /// </summary>
        public static string TXT_SEED_VEHICLE_8_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_8_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N35.
        /// </summary>
        public static string TXT_SEED_VEHICLE_8_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_8_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N75.
        /// </summary>
        public static string TXT_SEED_VEHICLE_8_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_8_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAGLE.
        /// </summary>
        public static string TXT_SEED_VEHICLE_9_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_9_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAF.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANIA.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_2_MODEL_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_2_MODEL_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANIA.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERCEDES.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAULT.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_4_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_4_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLVO.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_5_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_5_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVECO.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_6_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_6_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAN.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_7_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_7_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISUZU.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_8_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_8_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENNIS.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_9_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_9_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_MODEL_1_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_MODEL_1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_MODEL_2_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_MODEL_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XF.
        /// </summary>
        public static string TXT_SEED_VEHICLE_MAKE_MODEL_3_NAME {
            get {
                return ResourceManager.GetString("TXT_SEED_VEHICLE_MAKE_MODEL_3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - 6 year calibration.
        /// </summary>
        public static string TXT_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string TXT_SUNDAY {
            get {
                return ResourceManager.GetString("TXT_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Default).
        /// </summary>
        public static string TXT_TECHNICIAN_DEFAULT {
            get {
                return ResourceManager.GetString("TXT_TECHNICIAN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string TXT_THURSDAY {
            get {
                return ResourceManager.GetString("TXT_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string TXT_TUESDAY {
            get {
                return ResourceManager.GetString("TXT_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - 2 year inspection.
        /// </summary>
        public static string TXT_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string TXT_WEDNESDAY {
            get {
                return ResourceManager.GetString("TXT_WEDNESDAY", resourceCulture);
            }
        }
    }
}
