//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcal.EmailWorker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webcal.EmailWorker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending MAPI Email. Error: {0} (code = {1})..
        /// </summary>
        internal static string ERR_ERROR_SEND_MAPI_EMAIL {
            get {
                return ResourceManager.GetString("ERR_ERROR_SEND_MAPI_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure..
        /// </summary>
        internal static string TXT_LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("TXT_LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Ambiguous recipient..
        /// </summary>
        internal static string TXT_MAPI_AMBIGUOUS_RECIPIENT {
            get {
                return ResourceManager.GetString("TXT_MAPI_AMBIGUOUS_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment not found..
        /// </summary>
        internal static string TXT_MAPI_ATTACHMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment open failure..
        /// </summary>
        internal static string TXT_MAPI_ATTACHMENT_OPEN_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_OPEN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment Write Failure..
        /// </summary>
        internal static string TXT_MAPI_ATTACHMENT_WRITE_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_WRITE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Bad recipient type..
        /// </summary>
        internal static string TXT_MAPI_BAD_RECIPIENT_TYPE {
            get {
                return ResourceManager.GetString("TXT_MAPI_BAD_RECIPIENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Block too small..
        /// </summary>
        internal static string TXT_MAPI_BLOCK_TOO_SMALL {
            get {
                return ResourceManager.GetString("TXT_MAPI_BLOCK_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Disk full..
        /// </summary>
        internal static string TXT_MAPI_DISK_FULL {
            get {
                return ResourceManager.GetString("TXT_MAPI_DISK_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Failure..
        /// </summary>
        internal static string TXT_MAPI_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Insufficient memory..
        /// </summary>
        internal static string TXT_MAPI_INSUFFICIENT_MEMORY {
            get {
                return ResourceManager.GetString("TXT_MAPI_INSUFFICIENT_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid edit fields..
        /// </summary>
        internal static string TXT_MAPI_INVALID_EDIT_FIELDS {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_EDIT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid message..
        /// </summary>
        internal static string TXT_MAPI_INVALID_MESSAGE {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid parameter..
        /// </summary>
        internal static string TXT_MAPI_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid Recipients..
        /// </summary>
        internal static string TXT_MAPI_INVALID_RECIPIENTS {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid session..
        /// </summary>
        internal static string TXT_MAPI_INVALID_SESSION {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Message in use..
        /// </summary>
        internal static string TXT_MAPI_MESSAGE_IN_USE {
            get {
                return ResourceManager.GetString("TXT_MAPI_MESSAGE_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Network failure..
        /// </summary>
        internal static string TXT_MAPI_NETWORK_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_NETWORK_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI No Library..
        /// </summary>
        internal static string TXT_MAPI_NO_LIBRARY {
            get {
                return ResourceManager.GetString("TXT_MAPI_NO_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI No messages..
        /// </summary>
        internal static string TXT_MAPI_NO_MESSAGES {
            get {
                return ResourceManager.GetString("TXT_MAPI_NO_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Not supported..
        /// </summary>
        internal static string TXT_MAPI_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TXT_MAPI_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Text too large..
        /// </summary>
        internal static string TXT_MAPI_TEXT_TOO_LARGE {
            get {
                return ResourceManager.GetString("TXT_MAPI_TEXT_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI too many files..
        /// </summary>
        internal static string TXT_MAPI_TOO_MANY_FILES {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI too many recipients..
        /// </summary>
        internal static string TXT_MAPI_TOO_MANY_RECIPIENTS {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Too many sessions..
        /// </summary>
        internal static string TXT_MAPI_TOO_MANY_SESSIONS {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Type not supported..
        /// </summary>
        internal static string TXT_MAPI_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TXT_MAPI_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Unknown recipient..
        /// </summary>
        internal static string TXT_MAPI_UNKNOWN_RECIPEIENT {
            get {
                return ResourceManager.GetString("TXT_MAPI_UNKNOWN_RECIPEIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending via MAPI.
        /// </summary>
        internal static string TXT_SENDING_VIA_MAPI {
            get {
                return ResourceManager.GetString("TXT_SENDING_VIA_MAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending via SMTP.
        /// </summary>
        internal static string TXT_SENDING_VIA_SMTP {
            get {
                return ResourceManager.GetString("TXT_SENDING_VIA_SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Aborted..
        /// </summary>
        internal static string TXT_USER_ABORTED {
            get {
                return ResourceManager.GetString("TXT_USER_ABORTED", resourceCulture);
            }
        }
    }
}
