//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TachographReader.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TachographReader.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending MAPI Email. Error: {0} (code = {1})..
        /// </summary>
        public static string ERR_ERROR_SEND_MAPI_EMAIL {
            get {
                return ResourceManager.GetString("ERR_ERROR_SEND_MAPI_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the requested .Net Framework Data Provider.  It may not be installed..
        /// </summary>
        public static string ERR_UNABLE_FIND_DATA_PROVIDER {
            get {
                return ResourceManager.GetString("ERR_UNABLE_FIND_DATA_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.  SQL CE 4.0 may not be installed..
        /// </summary>
        public static string ERR_UNABLE_FIND_SQL_CE {
            get {
                return ResourceManager.GetString("ERR_UNABLE_FIND_SQL_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find suitable PDF executable path.
        /// </summary>
        public static string ERR_UNABLE_FIND_SUITABLE_PDF_EXECUTABLE_PATH {
            get {
                return ResourceManager.GetString("ERR_UNABLE_FIND_SUITABLE_PDF_EXECUTABLE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; has the following errors:
        ///.
        /// </summary>
        public static string EXC_ENTITY_VALIDATION_ERRORS {
            get {
                return ResourceManager.GetString("EXC_ENTITY_VALIDATION_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image could not be loaded.
        /// </summary>
        public static string EXC_IMAGE_COULD_NOT_BE_LOADED {
            get {
                return ResourceManager.GetString("EXC_IMAGE_COULD_NOT_BE_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find font &apos;Lucida Console&apos;.  Printing cannot continue.
        /// </summary>
        public static string EXC_UNABLE_FIND_LABEL_FONT {
            get {
                return ResourceManager.GetString("EXC_UNABLE_FIND_LABEL_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}
        ///.
        /// </summary>
        public static string EXC_VALIDATION_ERROR_PROPERTY {
            get {
                return ResourceManager.GetString("EXC_VALIDATION_ERROR_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. Trying again in {0} seconds....
        /// </summary>
        public static string TXT_ATTEMPT_FAILED {
            get {
                return ResourceManager.GetString("TXT_ATTEMPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string TXT_CALIBRATION_DATE {
            get {
                return ResourceManager.GetString("TXT_CALIBRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE: .
        /// </summary>
        public static string TXT_DATE {
            get {
                return ResourceManager.GetString("TXT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Calibration.
        /// </summary>
        public static string TXT_DATE_OF_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DATE_OF_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string TXT_DEMO {
            get {
                return ResourceManager.GetString("TXT_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Digital initial calibration.
        /// </summary>
        public static string TXT_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Digital 2 year calibration.
        /// </summary>
        public static string TXT_DIGITAL_TWO_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TWO_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        public static string TXT_FAILED {
            get {
                return ResourceManager.GetString("TXT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TXT_INFORMATION {
            get {
                return ResourceManager.GetString("TXT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Installation / Initial calibration.
        /// </summary>
        public static string TXT_INSTALLATION_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_INSTALLATION_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string TXT_LABEL_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number: {0}.
        /// </summary>
        public static string TXT_LABEL_CUSTOMER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Initial.
        /// </summary>
        public static string TXT_LABEL_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital 2yr.
        /// </summary>
        public static string TXT_LABEL_DIGITAL_TWO_YEAR {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_TWO_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Calibration.
        /// </summary>
        public static string TXT_LABEL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K={0} imp/km.
        /// </summary>
        public static string TXT_LABEL_K_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_K_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L={0} mm.
        /// </summary>
        public static string TXT_LABEL_L_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_L_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Work.
        /// </summary>
        public static string TXT_LABEL_MINOR_WORK {
            get {
                return ResourceManager.GetString("TXT_LABEL_MINOR_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration.
        /// </summary>
        public static string TXT_LABEL_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal no={0}.
        /// </summary>
        public static string TXT_LABEL_SEAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SEAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No: {0}.
        /// </summary>
        public static string TXT_LABEL_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6yr Calibration.
        /// </summary>
        public static string TXT_LABEL_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2yr Inspection.
        /// </summary>
        public static string TXT_LABEL_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_LABEL_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre size: {0}.
        /// </summary>
        public static string TXT_LABEL_TYRE_SIZE {
            get {
                return ResourceManager.GetString("TXT_LABEL_TYRE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN={0}.
        /// </summary>
        public static string TXT_LABEL_VIN {
            get {
                return ResourceManager.GetString("TXT_LABEL_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W={0} imp/km.
        /// </summary>
        public static string TXT_LABEL_W_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_W_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure..
        /// </summary>
        public static string TXT_LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("TXT_LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Ambiguous recipient..
        /// </summary>
        public static string TXT_MAPI_AMBIGUOUS_RECIPIENT {
            get {
                return ResourceManager.GetString("TXT_MAPI_AMBIGUOUS_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment not found..
        /// </summary>
        public static string TXT_MAPI_ATTACHMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment open failure..
        /// </summary>
        public static string TXT_MAPI_ATTACHMENT_OPEN_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_OPEN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Attachment Write Failure..
        /// </summary>
        public static string TXT_MAPI_ATTACHMENT_WRITE_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_ATTACHMENT_WRITE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Bad recipient type..
        /// </summary>
        public static string TXT_MAPI_BAD_RECIPIENT_TYPE {
            get {
                return ResourceManager.GetString("TXT_MAPI_BAD_RECIPIENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Block too small..
        /// </summary>
        public static string TXT_MAPI_BLOCK_TOO_SMALL {
            get {
                return ResourceManager.GetString("TXT_MAPI_BLOCK_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Disk full..
        /// </summary>
        public static string TXT_MAPI_DISK_FULL {
            get {
                return ResourceManager.GetString("TXT_MAPI_DISK_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Failure..
        /// </summary>
        public static string TXT_MAPI_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Insufficient memory..
        /// </summary>
        public static string TXT_MAPI_INSUFFICIENT_MEMORY {
            get {
                return ResourceManager.GetString("TXT_MAPI_INSUFFICIENT_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid edit fields..
        /// </summary>
        public static string TXT_MAPI_INVALID_EDIT_FIELDS {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_EDIT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid message..
        /// </summary>
        public static string TXT_MAPI_INVALID_MESSAGE {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid parameter..
        /// </summary>
        public static string TXT_MAPI_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid Recipients..
        /// </summary>
        public static string TXT_MAPI_INVALID_RECIPIENTS {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Invalid session..
        /// </summary>
        public static string TXT_MAPI_INVALID_SESSION {
            get {
                return ResourceManager.GetString("TXT_MAPI_INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Message in use..
        /// </summary>
        public static string TXT_MAPI_MESSAGE_IN_USE {
            get {
                return ResourceManager.GetString("TXT_MAPI_MESSAGE_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Network failure..
        /// </summary>
        public static string TXT_MAPI_NETWORK_FAILURE {
            get {
                return ResourceManager.GetString("TXT_MAPI_NETWORK_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI No Library..
        /// </summary>
        public static string TXT_MAPI_NO_LIBRARY {
            get {
                return ResourceManager.GetString("TXT_MAPI_NO_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI No messages..
        /// </summary>
        public static string TXT_MAPI_NO_MESSAGES {
            get {
                return ResourceManager.GetString("TXT_MAPI_NO_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Not supported..
        /// </summary>
        public static string TXT_MAPI_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TXT_MAPI_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Text too large..
        /// </summary>
        public static string TXT_MAPI_TEXT_TOO_LARGE {
            get {
                return ResourceManager.GetString("TXT_MAPI_TEXT_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI too many files..
        /// </summary>
        public static string TXT_MAPI_TOO_MANY_FILES {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI too many recipients..
        /// </summary>
        public static string TXT_MAPI_TOO_MANY_RECIPIENTS {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Too many sessions..
        /// </summary>
        public static string TXT_MAPI_TOO_MANY_SESSIONS {
            get {
                return ResourceManager.GetString("TXT_MAPI_TOO_MANY_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Type not supported..
        /// </summary>
        public static string TXT_MAPI_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TXT_MAPI_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI Unknown recipient..
        /// </summary>
        public static string TXT_MAPI_UNKNOWN_RECIPEIENT {
            get {
                return ResourceManager.GetString("TXT_MAPI_UNKNOWN_RECIPEIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of retries has been reached.
        /// </summary>
        public static string TXT_MAX_RETRIES_REACHED {
            get {
                return ResourceManager.GetString("TXT_MAX_RETRIES_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        public static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred whilst performing the operation.  See below for details;
        ///
        ///{0}.
        /// </summary>
        public static string TXT_ONE_OR_MORE_ERRORS {
            get {
                return ResourceManager.GetString("TXT_ONE_OR_MORE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to print....
        /// </summary>
        public static string TXT_PREPARING_TO_PRINT {
            get {
                return ResourceManager.GetString("TXT_PREPARING_TO_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print complete, tidying up..
        /// </summary>
        public static string TXT_PRINT_COMPLETE {
            get {
                return ResourceManager.GetString("TXT_PRINT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string TXT_QUESTION {
            get {
                return ResourceManager.GetString("TXT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        public static string TXT_READNG {
            get {
                return ResourceManager.GetString("TXT_READNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Recalibration.
        /// </summary>
        public static string TXT_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request failed with exception: {0}.
        /// </summary>
        public static string TXT_REQUEST_FAIlED_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("TXT_REQUEST_FAIlED_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request failed with unexpected exception: {0}.
        /// </summary>
        public static string TXT_REQUEST_FAILED_WITH_UNEXPECTED_EXCEPTION {
            get {
                return ResourceManager.GetString("TXT_REQUEST_FAILED_WITH_UNEXPECTED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out.
        /// </summary>
        public static string TXT_REQUEST_TIMED_OUT {
            get {
                return ResourceManager.GetString("TXT_REQUEST_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending via MAPI.
        /// </summary>
        public static string TXT_SENDING_VIA_MAPI {
            get {
                return ResourceManager.GetString("TXT_SENDING_VIA_MAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending via SMTP.
        /// </summary>
        public static string TXT_SENDING_VIA_SMTP {
            get {
                return ResourceManager.GetString("TXT_SENDING_VIA_SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent back a fault: {0}.
        /// </summary>
        public static string TXT_SERVER_SENT_A_FAULT {
            get {
                return ResourceManager.GetString("TXT_SERVER_SENT_A_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - 6 year calibration.
        /// </summary>
        public static string TXT_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillray.
        /// </summary>
        public static string TXT_SKILLRAY {
            get {
                return ResourceManager.GetString("TXT_SKILLRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string TXT_STARTING {
            get {
                return ResourceManager.GetString("TXT_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - 2 year inspection.
        /// </summary>
        public static string TXT_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Aborted..
        /// </summary>
        public static string TXT_USER_ABORTED {
            get {
                return ResourceManager.GetString("TXT_USER_ABORTED", resourceCulture);
            }
        }
    }
}
