//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TachoReaderLicensingWebsite.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public string LKey { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.Guid AccessID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
