//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcal.LabelPrintWorker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webcal.LabelPrintWorker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find font &apos;Lucida Console&apos;.  Printing cannot continue.
        /// </summary>
        public static string EXC_UNABLE_FIND_LABEL_FONT {
            get {
                return ResourceManager.GetString("EXC_UNABLE_FIND_LABEL_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE: {0}.
        /// </summary>
        public static string TXT_CALIBRATION_DATE {
            get {
                return ResourceManager.GetString("TXT_CALIBRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE: .
        /// </summary>
        public static string TXT_DATE {
            get {
                return ResourceManager.GetString("TXT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string TXT_DEMO {
            get {
                return ResourceManager.GetString("TXT_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Digital initial calibration.
        /// </summary>
        public static string TXT_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Digital 2 year calibration.
        /// </summary>
        public static string TXT_DIGITAL_TWO_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_DIGITAL_TWO_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Installation / Initial calibration.
        /// </summary>
        public static string TXT_INSTALLATION_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_INSTALLATION_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string TXT_LABEL_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number: {0}.
        /// </summary>
        public static string TXT_LABEL_CUSTOMER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_CUSTOMER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Initial.
        /// </summary>
        public static string TXT_LABEL_DIGITAL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital 2yr.
        /// </summary>
        public static string TXT_LABEL_DIGITAL_TWO_YEAR {
            get {
                return ResourceManager.GetString("TXT_LABEL_DIGITAL_TWO_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Calibration.
        /// </summary>
        public static string TXT_LABEL_INITIAL_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_INITIAL_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K={0} imp/km.
        /// </summary>
        public static string TXT_LABEL_K_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_K_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L={0} mm.
        /// </summary>
        public static string TXT_LABEL_L_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_L_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Work.
        /// </summary>
        public static string TXT_LABEL_MINOR_WORK {
            get {
                return ResourceManager.GetString("TXT_LABEL_MINOR_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration.
        /// </summary>
        public static string TXT_LABEL_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal no={0}.
        /// </summary>
        public static string TXT_LABEL_SEAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SEAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No: {0}.
        /// </summary>
        public static string TXT_LABEL_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("TXT_LABEL_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6yr Calibration.
        /// </summary>
        public static string TXT_LABEL_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_LABEL_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2yr Inspection.
        /// </summary>
        public static string TXT_LABEL_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_LABEL_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre size: {0}.
        /// </summary>
        public static string TXT_LABEL_TYRE_SIZE {
            get {
                return ResourceManager.GetString("TXT_LABEL_TYRE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN={0}.
        /// </summary>
        public static string TXT_LABEL_VIN {
            get {
                return ResourceManager.GetString("TXT_LABEL_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W={0} imp/km.
        /// </summary>
        public static string TXT_LABEL_W_FACTOR {
            get {
                return ResourceManager.GetString("TXT_LABEL_W_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Minor Work.
        /// </summary>
        public static string TXT_MINOR_WORK_DETAILS {
            get {
                return ResourceManager.GetString("TXT_MINOR_WORK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to print....
        /// </summary>
        public static string TXT_PREPARING_TO_PRINT {
            get {
                return ResourceManager.GetString("TXT_PREPARING_TO_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Recalibration.
        /// </summary>
        public static string TXT_RECALIBRATION {
            get {
                return ResourceManager.GetString("TXT_RECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - 6 year calibration.
        /// </summary>
        public static string TXT_SIX_YEAR_CALIBRATION {
            get {
                return ResourceManager.GetString("TXT_SIX_YEAR_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillray.
        /// </summary>
        public static string TXT_SKILLRAY {
            get {
                return ResourceManager.GetString("TXT_SKILLRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - 2 year inspection.
        /// </summary>
        public static string TXT_TWO_YEAR_INSPECTION {
            get {
                return ResourceManager.GetString("TXT_TWO_YEAR_INSPECTION", resourceCulture);
            }
        }
    }
}
